### ISSUE TITLE
Getting Error: No element found for selector: input[name=rememberMe]

### ISSUE THREAD

**Issue by zefir6** [treetrum/amazon-kindle-bulk-downloader#120]
Getting 
Error: No element found for selector: input[name=rememberMe]

full error

```npm run start --baseUrl https://www.amazon.com                                                           

> amazon-kindle-bulk-downloader@1.0.0 start
> ts-node src/index.ts https://www.amazon.com

Getting credentials
Got credentials
Filling username
Filling password
/Users/user1/amazon-kindle-bulk-downloader/node_modules/puppeteer-core/src/util/assert.ts:19
    throw new Error(message);
          ^
Error: No element found for selector: input[name=rememberMe]
    at assert (/Users/zefir/projects/amazon-kindle-bulk-downloader/node_modules/puppeteer-core/src/util/assert.ts:19:11)
    at CdpFrame.click (/Users/zefir/projects/amazon-kindle-bulk-downloader/node_modules/puppeteer-core/src/api/Frame.ts:1053:11)
    at async login (/Users/zefir/projects/amazon-kindle-bulk-downloader/src/index.ts:40:9)
    at async main (/Users/zefir/projects/amazon-kindle-bulk-downloader/src/index.ts:365:13)```

**Comment by treetrum** [comment]
Hi there, I only have limited time to work on this project. For now, your best bet will be to log in manually using the `--manualAuth` cli option which should work around this problem for the time being.
